<?php
defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
require APPPATH . '/libraries/REST_Controller.php';

// use namespace
use Restserver\Libraries\REST_Controller;

class Users extends REST_Controller {

	
    
    public function index_get()
    {
        $this->load->model('user');
        $users = $this->user->get_all();

        $id = $this->get('id');
        $param = $this->get('param');

        // If the id parameter doesn't exist return all the users

        if ($id === NULL)
        {
			if($param == 'getLogin'){
			$user_id = $this->user->getValidLogins($this->get('username'),$this->get('password'));
			if($user_id > 0){
				$this->response($user_id, REST_Controller::HTTP_OK); // CREATED (201) being the HTTP response code
			} else{
				$this->response(0, REST_Controller::HTTP_NOT_FOUND); // CREATED (201) being the HTTP response code
			}
					
		} else{
            // Check if the users data store contains users (in case the database result returns NULL)
            if ($users)
            {
                // Set the response and exit
                $this->response($users, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
		}
        }

        // Find and return a single record for a particular user.
        else {
            $id = (int) $id;

            // Validate the id.
            if ($id <= 0)
            {
                // Invalid id, set the response and exit.
                $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }

            // Get the user from the array, using the id as key for retrieval.
            // Usually a model is to be used for this.

            $user = NULL;

            if (!empty($users))
            {
                foreach ($users as $key => $value)
                {
                    if (isset($value->user_id) && $value->user_id == $id)
                    {
                        $user = $value;
                    }
                }
            }

            if (!empty($user))
            {
                $this->set_response($user, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                $this->set_response([
                    'status' => FALSE,
                    'message' => 'User could not be found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }
    }
    
	public function index_put(){
		$this->load->model('user');
		
		if($this->input->get('id') != null){
			 $insert_id = $this->user->update_entry($this->put(),$this->input->get('id'));
        $message = [
            'id' => $this->input->get('id'), 
            'username' => $this->put('username'),
            'displayname' => $this->put('displayname'),
            'tipe'  => $this->put('tipe'),
            'alamat'  => $this->put('alamat'),
            'ktp'  => $this->put('ktp'),
            'tgl_lahir'  => $this->put('tgl_lahir'),
            'message' => 'Updated a user'
        ];

        $this->set_response($message, REST_Controller::HTTP_OK); // HTTP ok response
		} else{
			$message = [
            'message' => 'Id user null'
			];
			 $this->response($message, REST_Controller::HTTP_BAD_REQUEST);
		}
       
	}
	
    public function index_post()
    {
        $this->load->model('user');
		$param = $this->get('param');
	
			$insert_id = $this->user->insert_entry($_POST);
			// $this->some_model->update_user( ... );
			$message = [
				'id' => $insert_id, // Automatically generated by the model
				'username' => $this->post('username'),
				'displayname' => $this->post('displayname'),
				'tipe'  => $this->post('tipe'),
				'alamat'  => $this->put('alamat'),
				'ktp'  => $this->put('ktp'),
				'tgl_lahir'  => $this->put('tgl_lahir'),
				'message' => 'Added a resource'
			];

			$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
		
    }
    
    public function index_delete()
    {
        $this->load->model('user');
        $id = $this->input->get('id');

        // Validate the id.
        if ($id <= 0)
        {
            // Set the response and exit
			$message = [
                'id' => $id,
                'message' => 'error'
				];
            $this->response($message, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        } else{
            $status = $this->user->delete_entry($id);
            // $this->some_model->delete_something($id);
            if($status){
                $message = [
                'id' => $id,
                'message' => 'Deleted the resource'
            ];
                $this->set_response($message, REST_Controller::HTTP_OK); //response ok
            } else{
                // Set the response and exit
                $this->response([
                    'status' => FALSE,
                    'message' => 'No users were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
            
            
        }

    }
}